language: node_js
sudo: false
node_js:
  - '4.2.1'
before_install:
  - openssl aes-256-cbc -K $encrypted_de8967fa70d8_key -iv $encrypted_de8967fa70d8_iv
    -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - git config --global user.name "YuLun Shih"
  - git config --global user.email shih@yulun.me
  - npm install
  - git clone -b gh-pages https://github.com/imZack/imZack.github.io .deploy
script:
  - hexo generate
  - hexo deploy
branches:
  only:
    - master
